config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :shopping_carts
#  get 'products/index'

#  get 'products/new'

#  get 'products/edit'

#  get 'products/show'

#  get 'products/delete'
   root 'store#index', as: 'store_index'
   resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :shopping_cart
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  scope :search, lambda {|query| where(["title LIKE ?","%#{query}%" ])}
  validates :title, :description, :image_url, presence: true

  validates :title, length: {minimux: 1, maximum: 20}
  validates :title, uniqueness: true

  validates :price, numericality: {greater_than_or_equal_to: 0.01}


  validates :image_url, allow_blank: true, format: {

      with: %r{\.(gif|jpg|png)\z}i,
      message: 'must be a url for GIF, JPG or PNG image.'
  }

  private
   def ensure_not_referenced_by_any_line_item
     unless line_items.empty?
       errors.add(:base, 'Line Items present')
       throw :abort
     end
   end

end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  def add_product(product)
    current_item  = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/current_cart.rb
module CurrentCart
   private
     
     def set_cart
       @cart = ShoppingCart.find(session[:shoppingcart_id])
     rescue ActiveRecord::RecordNotFound
       @cart = ShoppingCart.create
       session[:shoppingcart_id] = @cart.id
     end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)
    # @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.shopping_cart, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :shopping_cart_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_products, only: [:show, :edit,:update, :destroy]

  def index
    @products = Product.all #why can't change to @product #
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save

      redirect_to(product_path(@product))
    else
      render('new')

    end
  end

  def edit
  end

  def update
    @product.update_attributes(product_params)
    redirect_to(product_path(@product))
  end

  def show

  end

  def destroy

     @product.destroy
     redirect_to(products_url) #why can't use render('root')
  end

  def set_products
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title,:description,:image_url,:price)
  end

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :set_shopping_cart, only: [:show, :edit, :update, :destroy]

  # GET /shopping_carts
  # GET /shopping_carts.json
  def index
    @shopping_carts = ShoppingCart.all
  end

  # GET /shopping_carts/1
  # GET /shopping_carts/1.json
  def show
  end

  # GET /shopping_carts/new
  def new
    @shopping_cart = ShoppingCart.new
  end

  # GET /shopping_carts/1/edit
  def edit
  end

  # POST /shopping_carts
  # POST /shopping_carts.json
  def create
    @shopping_cart = ShoppingCart.new(shopping_cart_params)

    respond_to do |format|
      if @shopping_cart.save
        format.html { redirect_to @shopping_cart, notice: 'Shopping cart was successfully created.' }
        format.json { render :show, status: :created, location: @shopping_cart }
      else
        format.html { render :new }
        format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_carts/1
  # PATCH/PUT /shopping_carts/1.json
  def update
    respond_to do |format|
      if @shopping_cart.update(shopping_cart_params)
        format.html { redirect_to @shopping_cart, notice: 'Shopping cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopping_cart }
      else
        format.html { render :edit }
        format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_carts/1
  # DELETE /shopping_carts/1.json
  def destroy
    @shopping_cart.destroy
    respond_to do |format|
      format.html { redirect_to shopping_carts_url, notice: 'Shopping cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_cart
      @shopping_cart = ShoppingCart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_cart_params
      params.fetch(:shopping_cart, {})
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.order(price: "desc" )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application',
                             'data-turbolinks-track': 'reload' %>
</head>

<body class=""<%= controller.controller_name %>">
 <div id="banner">
  <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
  <span class="title"><%= @page_title%></span>
 </div>
  <div id="columns">
   <div id="side">
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/questions">Questions</a></li>
      <li><a href="/news">News</a></li>
      <li><a href="/contact">Contact</a></li>
    </ul>
   </div>
  <div id="main">
    <%= yield %>
  </div>
</div>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :line_item_product_id %>
  </div>

  <div class="field">
    <%= form.label :shopping_cart_id %>
    <%= form.text_field :shopping_cart_id, id: :line_item_shopping_cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Shopping cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.shopping_cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

</ul>
<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Shopping cart:</strong>
  <%= @line_item.shopping_cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true) do |form| %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :product_title %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, id: :description, size: "40x20"%>
    </div>

    <div class="field">
      <%= form.label :image_url %>
      <%= form.text_field :image_url, id: :product_image_url %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price, id: :product_price %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/products/delete.html.erb
<h1>Products#delete</h1>
<p>Find me in app/views/products/delete.html.erb</p>

app/views/products/edit.html.erb
<h1>Edit</h1>

<%= render 'form', product: @product%>

<%= link_to 'show',product_path(@product)%>
<%= link_to 'back', products_path%>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<%= form_with(model: @product, local: true) do |product|%>
    <%=label(:q,"Search")%>
    <%=product.text_field(:q)%>
    <%=product.submit("Search")%>
    <%end%>

<table>
  <tfoot>
  <tr>
    <td colspan="3">
      <%= link_to 'New product', new_product_path %>
    </td>
  </tr>
  </tfoot>

  <tbody>
  <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

        <td class="image">
           <%= image_tag(product.image_url, class: 'list_image',alt: "no picture")%>
        </td>

        <td class="description">
          <h1><%= product.title %></h1>
          <p>
            <%= truncate(strip_tags(product.description),  #truncate displays first 8 characters #
                         length: 80) %>
          </p>

        <td class="actions">
          <ul>
            <li><%= link_to 'Show', product %></li>
            <li><%= link_to 'Edit', edit_product_path(product) %></li>
            <li>
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
            </li>
          </ul>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<br>
<br>

app/views/products/new.html.erb
<h1>Create Product</h1>

<%= render 'form', product: @product%>
<%= link_to'Back', products_path%>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shopping_carts/_form.html.erb
<%= form_with(model: shopping_cart, local: true) do |form| %>
  <% if shopping_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shopping_cart.errors.count, "error") %> prohibited this shopping_cart from being saved:</h2>

      <ul>
      <% shopping_cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shopping_carts/edit.html.erb
<h1>Editing Shopping Cart</h1>

<%= render 'form', shopping_cart: @shopping_cart %>

<%= link_to 'Show', @shopping_cart %> |
<%= link_to 'Back', shopping_carts_path %>

app/views/shopping_carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shopping Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_carts.each do |shopping_cart| %>
      <tr>
        <td><%= link_to 'Show', shopping_cart %></td>
        <td><%= link_to 'Edit', edit_shopping_cart_path(shopping_cart) %></td>
        <td><%= link_to 'Destroy', shopping_cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping Cart', new_shopping_cart_path %>

app/views/shopping_carts/new.html.erb
<h1>New Shopping Cart</h1>

<%= render 'form', shopping_cart: @shopping_cart %>

<%= link_to 'Back', shopping_carts_path %>

app/views/shopping_carts/show.html.erb
<p id="notice"><%= notice %></p>


<h2>Your Pragmatic Cart</h2>
<ul>
  <% @shopping_cart.line_items.each do |item| %>
      <li><%= item.quantity%> &times; <%= item.product.title %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_shopping_cart_path(@shopping_cart) %> |
<%= link_to 'Back', store_index_path %>

app/views/store/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Your Pragmatic Catalog</h1>

<% cache @products do%>
    <% @products.each do |product|%>
        <% cache product do%>
        <div class ="entry">
        <%= image_tag(product.image_url, alt: "there is no picture") %>
        <h3><%= product.title %></h3>
        <%=sanitize(product.description) %>
        <div class="price_line">
        <span class="price"><%= number_to_currency(product.price) %></span>
          <%= button_to 'Add to Cart', line_items_path(product_id: product)%>
        </div>
    </div>
        <% end %>
    <% end %>
<% end %>